# Generated by Django 4.0.6 on 2022-08-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prev_seasons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasons',
            name='id',
        ),
        migrations.AlterField(
            model_name='seasons',
            name='season',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
