# Generated by Django 4.1 on 2022-09-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('season', models.CharField(max_length=255)),
                ('gw', models.IntegerField()),
                ('home_id', models.IntegerField()),
                ('away_id', models.IntegerField()),
                ('finished', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Gameweek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gameweek', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('second_name', models.CharField(max_length=255)),
                ('known_as', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('team_id', models.IntegerField()),
                ('position', models.IntegerField()),
                ('fpl_cost', models.IntegerField()),
                ('fpl_total_points', models.IntegerField()),
                ('fpl_form', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('short_name', models.CharField(max_length=255)),
                ('strength', models.IntegerField()),
                ('strength_overall_home', models.IntegerField()),
                ('strength_overall_away', models.IntegerField()),
                ('strength_attack_home', models.IntegerField()),
                ('strength_attack_away', models.IntegerField()),
                ('strength_defence_home', models.IntegerField()),
                ('strength_defence_away', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserSquad',
            fields=[
                ('squad_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user', models.IntegerField()),
                ('gameweek', models.IntegerField()),
                ('player', models.IntegerField()),
                ('starter', models.BooleanField()),
                ('is_captain', models.BooleanField()),
                ('is_vice_captain', models.BooleanField()),
            ],
        ),
    ]
