# Generated by Django 4.1 on 2022-09-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fpl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='fpl_form',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
